# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.central_widget = QtWidgets.QWidget(LoginWindow)
        self.central_widget.setGeometry(QtCore.QRect(200, 100, 400, 400))
        self.central_widget.setStyleSheet("QWidget {\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    border-radius: 15px;\n"
"}")
        self.central_widget.setObjectName("central_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.central_widget)
        self.verticalLayout.setContentsMargins(30, 40, 30, 40)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_label = QtWidgets.QLabel(self.central_widget)
        self.title_label.setStyleSheet("QLabel {\n"
"    font-size: 24px;\n"
"    font-weight: bold;\n"
"    color: #333333;\n"
"    margin-bottom: 20px;\n"
"}")
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.verticalLayout.addWidget(self.title_label)
        self.type_layout = QtWidgets.QHBoxLayout()
        self.type_layout.setSpacing(30)
        self.type_layout.setObjectName("type_layout")
        self.student_radio = QtWidgets.QRadioButton(self.central_widget)
        self.student_radio.setStyleSheet("QRadioButton {\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.student_radio.setChecked(True)
        self.student_radio.setObjectName("student_radio")
        self.type_layout.addWidget(self.student_radio)
        self.admin_radio = QtWidgets.QRadioButton(self.central_widget)
        self.admin_radio.setStyleSheet("QRadioButton {\n"
"    font-size: 16px;\n"
"    color: #333333;\n"
"    padding: 5px;\n"
"}\n"
"QRadioButton::indicator {\n"
"    width: 20px;\n"
"    height: 20px;\n"
"}")
        self.admin_radio.setObjectName("admin_radio")
        self.type_layout.addWidget(self.admin_radio)
        self.verticalLayout.addLayout(self.type_layout)
        self.id_layout = QtWidgets.QHBoxLayout()
        self.id_layout.setObjectName("id_layout")
        self.id_label = QtWidgets.QLabel(self.central_widget)
        self.id_label.setStyleSheet("font-size: 16px; color: #333333;")
        self.id_label.setObjectName("id_label")
        self.id_layout.addWidget(self.id_label)
        self.id_input = QtWidgets.QLineEdit(self.central_widget)
        self.id_input.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    border: 2px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"    min-height: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50;\n"
"}")
        self.id_input.setObjectName("id_input")
        self.id_layout.addWidget(self.id_input)
        self.verticalLayout.addLayout(self.id_layout)
        self.name_layout = QtWidgets.QHBoxLayout()
        self.name_layout.setObjectName("name_layout")
        self.name_label = QtWidgets.QLabel(self.central_widget)
        self.name_label.setStyleSheet("font-size: 16px; color: #333333;")
        self.name_label.setObjectName("name_label")
        self.name_layout.addWidget(self.name_label)
        self.name_input = QtWidgets.QLineEdit(self.central_widget)
        self.name_input.setStyleSheet("QLineEdit {\n"
"    padding: 10px;\n"
"    border: 2px solid #CCCCCC;\n"
"    border-radius: 8px;\n"
"    background-color: white;\n"
"    font-size: 16px;\n"
"    min-height: 20px;\n"
"}\n"
"QLineEdit:focus {\n"
"    border-color: #4CAF50;\n"
"}")
        self.name_input.setObjectName("name_input")
        self.name_layout.addWidget(self.name_input)
        self.verticalLayout.addLayout(self.name_layout)
        self.login_button = QtWidgets.QPushButton(self.central_widget)
        self.login_button.setStyleSheet("QPushButton {\n"
"    background-color: #4CAF50;\n"
"    color: white;\n"
"    padding: 12px;\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    font-size: 18px;\n"
"    min-width: 200px;\n"
"    margin-top: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #45a049;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #3d8b40;\n"
"}")
        self.login_button.setObjectName("login_button")
        self.verticalLayout.addWidget(self.login_button, 0, QtCore.Qt.AlignHCenter)

        self.retranslateUi(LoginWindow)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "学生成绩管理系统 - 登录"))
        self.title_label.setText(_translate("LoginWindow", "学生成绩管理系统"))
        self.student_radio.setText(_translate("LoginWindow", "学生登录"))
        self.admin_radio.setText(_translate("LoginWindow", "管理员登录"))
        self.id_label.setText(_translate("LoginWindow", "学号:"))
        self.name_label.setText(_translate("LoginWindow", "姓名:"))
        self.login_button.setText(_translate("LoginWindow", "登录"))
